"""SQLite database for book metadata."""
import sqlite3
from pathlib import Path
from typing import List, Dict, Optional
from langsmith import traceable

DB_PATH = Path(__file__).parent.parent / "books.db"

def init_database():
    """Initialize the SQLite database and create books table."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # Create books table with numeric book_id
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS books (
            book_id INTEGER PRIMARY KEY AUTOINCREMENT,
            book_name TEXT NOT NULL,
            author_name TEXT NOT NULL,
            release_date TEXT NOT NULL,
            file_path TEXT
        )
    ''')
    
    # Check if we need to migrate from TEXT to INTEGER (rare case but good to handle)
    cursor.execute("PRAGMA table_info(books)")
    columns = [column for column in cursor.fetchall() if column[1] == 'book_id']
    if columns and columns[0][2].upper() == 'TEXT':
        print("⚠️ Warning: book_id is TEXT. Consider resetting the database for INTEGER IDs.")
    
    conn.commit()
    conn.close()
    print("✓ Database initialized.")

def add_book(book_name: str, author_name: str, release_date: str, file_path: str = None, book_id: int = None):
    """Add a book to the database.
    
    Args:
        book_name: Name of the book
        author_name: Author's name
        release_date: Release date (e.g., '1847-12-01')
        file_path: Path to the book file
        book_id: Optional numeric ID. If None, it will be autogenerated.
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    if book_id is not None:
        cursor.execute('''
            INSERT OR REPLACE INTO books (book_id, book_name, author_name, release_date, file_path)
            VALUES (?, ?, ?, ?, ?)
        ''', (book_id, book_name, author_name, release_date, file_path))
    else:
        # Prevent duplicates: Check if book with same name and author already exists
        cursor.execute('''
            SELECT book_id FROM books WHERE book_name = ? AND author_name = ?
        ''', (book_name, author_name))
        existing = cursor.fetchone()
        
        if existing:
            # Update existing record instead of inserting a new row
            cursor.execute('''
                UPDATE books SET release_date = ?, file_path = ?
                WHERE book_id = ?
            ''', (release_date, file_path, existing[0]))
            print(f"✓ Updated: {book_name}")
        else:
            cursor.execute('''
                INSERT INTO books (book_name, author_name, release_date, file_path)
                VALUES (?, ?, ?, ?)
            ''', (book_name, author_name, release_date, file_path))
            print(f"✓ Saved: {book_name}")
    
    conn.commit()
    conn.close()
    print(f"✓ Saved: {book_name}")

@traceable(name="Get Book Metadata from DB", run_type="tool")
def get_book(book_id: str) -> Optional[Dict]:
    """Get book metadata by book_id.
    
    Args:
        book_id: Unique book identifier
        
    Returns:
        Dictionary with book metadata or None if not found
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    cursor.execute('SELECT * FROM books WHERE book_id = ?', (book_id,))
    row = cursor.fetchone()
    conn.close()
    
    if row:
        return {
            'book_id': row[0],
            'book_name': row[1],
            'author_name': row[2],
            'release_date': row[3],
            'file_path': row[4]
        }
    return None

def get_all_books() -> List[Dict]:
    """Get all books from the database.
    
    Returns:
        List of dictionaries with book metadata
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    cursor.execute('SELECT * FROM books')
    rows = cursor.fetchall()
    conn.close()
    
    return [
        {
            'book_id': row[0],
            'book_name': row[1],
            'author_name': row[2],
            'release_date': row[3],
            'file_path': row[4]
        }
        for row in rows
    ]

@traceable(name="Search Books by Author in DB", run_type="tool")
def search_books_by_author(author_name: str) -> List[Dict]:
    """Search books by author name.
    
    Args:
        author_name: Author's name (partial match supported)
        
    Returns:
        List of matching books
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    cursor.execute('SELECT * FROM books WHERE author_name LIKE ?', (f'%{author_name}%',))
    rows = cursor.fetchall()
    conn.close()
    
    return [
        {
            'book_id': r[0],
            'book_name': r[1],
            'author_name': r[2],
            'release_date': r[3],
            'file_path': r[4]
        }
        for r in rows
    ]
